let data = [
  {
    id: 1,
    title: "A History of Russia Volume",
    price: 949,
    category: "History",
    description:
      "This new edition retains the features of the first edition that made it a popular choice in universities and colleges throughout the US, Canada and around the world. Moss's accessible history includes full treatment of everyday life, the role of women, rural life, law, religion, literature and art. ",
    Author: "Moss Walter G.",
    Publish:2000,
    image:
      "https://rukminim2.flixcart.com/image/416/416/k5y7tzk0/book/2/3/5/a-history-of-russia-volume-1-original-imafzgecxj3apzgu.jpeg?q=70&crop=false",
  },
  {
    id: 2,
    title: "Modern Indian History",
    price: 379,
    category: "History",
    description:
      "Modern History book launched by Study IQ Publications aims to address the syllabus of modern history holistically from the UPSC Civil Services Examinations perspective. The book has been updated as per the latest examination pattern. This book is specially designed for the main appearing aspirants",
    Author: "StudyIQ Publications",
    Publish: 1990,
    image:
      "https://rukminim2.flixcart.com/image/416/416/xif0q/regionalbooks/8/s/w/modern-indian-history-upsc-civil-services-exam-modern-indian-original-imagkfcv9hwfkvgp.jpeg?q=70&crop=false",
  },
  {
    id: 3,
    title: "The Metamorphosis",
    price: 89,
    category: "Horror",
    description: "The Metamorphosis by Franz Kafka is about a man named Gregor Samsa who becomes an insect. Until this incident, Gregor has worked hard to support his parents and sister. After he can no longer provide for their financial comfort, Gregor discovers that his family can indeed work.",
    Author: "Kafka Franz",
    Publish: 1915,
    image: "https://rukminim2.flixcart.com/image/416/416/l4fxh8w0/book/m/b/b/the-metamorphosis-original-imagfceu7dpvydqg.jpeg?q=70&crop=false",
  },
  {
    id: 4,
    title: "Samsara",
    price: 140,
    category: "Science fiction",
    description: "wandering, as well as world wherein the term connotes cyclic change. Saṃsāra, a fundamental concept in all Indian religions, is linked to the karma theory and refers to the belief that all living beings cyclically go through births and rebirths.",
    Author: "Garg Saksham",
    Publish: 2022,
    image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/m/q/g/samsara-original-imagkn793qwhydbn.jpeg?q=70&crop=false",
  },
  {
    id: 5,
    title: "Meri Jeevan Yatra",
    price: 180,
    category: "Biography",
    description: "Meri Jeevan Yatra was first published in 1944. The book describes his life, including his childhood, his life journey, and his professional experiences.",
    Author: "Kalam A.P.J Abdul",
    Publish: 1944,
    image: "https://rukminim2.flixcart.com/image/416/416/kiqbma80-0/book/p/r/p/meri-jeevan-yatra-original-imafygpgr6qhswyh.jpeg?q=70&crop=false",
  },
  {
    id: 6,
    title: "The Green Room",
    price: 195,
    category: "Horror",
    description: "She wears an old uniform,Nisha continued,pale white face, dark shadows around her eyes. She is often seen sitting on this very chair. And it is said that the chair is always found in front of the mirror no matter where you leave it.Rohan Agarwal has been appointed the manager of a play, and how excited he is to work with Chandni Joshi his childhood crush, and unfortunately, his senior! A happy-go-lucky high school boarder, ",
    Author: "Nag Mani",
    Publish: 2015,
    image: "https://rukminim2.flixcart.com/image/416/416/book/8/3/3/the-green-room-original-imaechxtkyqnnzmt.jpeg?q=70&crop=false",
  },
  {
    id: 7,
    title: "Transformers: Exodus",
    price: 2280,
    category: "Science fiction",
    description: "Transformers: Exodus is a novel written by Alex Irvine, which tells the story of the relationship between Orion Pax and Megatron long before the war broke out in Cybertron.",
    Author: "Irvine Alex",
    Publish: 2010,
    image: "https://rukminim2.flixcart.com/image/416/416/l5jxt3k0/book/a/o/6/transformers-exodus-original-imagg6tyyzqf8rb7.jpeg?q=70&crop=false",
  },
  {
    id: 8,
    title: "Jail Diary and Other Writings",
    price: 135,
    category: "Biography",
    description: "Bhagat Singh wrote this diary in the last two years of his young life while he was awaiting execution by the British rulers of India. His jail diary was handed over, along with other belongings to his father, Sardar Kishan Singh after his execution.",
    Author: "Singh Bhagat",
    Publish: 2020,
    image: "https://rukminim2.flixcart.com/image/416/416/kiow6fk0-0/book/q/e/0/jail-diary-and-other-writings-original-imafyf9fbggsw3ht.jpeg?q=70&crop=false",
  },
  {
    id: 9,
    title: "The Tragical History of Doctor Faustus",
    price: 125,
    category: "Science fiction",
    description: "The Tragical History of the Life and Death of Doctor Faustus, commonly referred to simply as Doctor Faustus, is an Elizabethan tragedy by Christopher Marlowe, based on German stories about the title character Faust. It was probably written in 1592 or 1593, shortly before Marlowe's death.",
    Author: "Marlowe Christopher",
    Publish: 1604,
    image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/w/d/0/the-tragical-history-of-doctor-faustus-english-original-imagz4yvxtwggfqe.jpeg?q=70&crop=false",
  },
  {
    id: 10,
    title: "Even in Death",
    price: 422,
    category: "Horror",
    description: "Even In Death, a collection of ten short stories, explores the thin line between love and hate; extreme emotions even death cannot destroy. Julie wants nothing more than to receive a flower bouquet from the hometown veterinarian.",
    Author: "Roman Lilith",
    Publish: 2021,
    image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/0/t/q/even-in-death-original-imagxypuhp8rhegj.jpeg?q=70&crop=false",
  },
  {
    id: 11,
    title: "Love Makes the Dead Alive",
    price: 195,
    category: "Horror",
    description: "An ominous accident puts Karan, a skeptical boy, in between the Demon and the Divine. A series of mind numbing haunts sets him on a perilous journey to battle an evil power. Vasuki's tormented soul finds Karan to quash virulent Pishach. Karan sets her soul free, but at a heavy price.",
    Author: "Dinesh Singh",
        Publish: 2018,

    image: "https://rukminim2.flixcart.com/image/416/416/kjiwfbk0-0/book/j/p/3/love-makes-the-dead-alive-original-imafz2r9zkxe3yb8.jpeg?q=70&crop=false",
  },
  {
    id: 12,
    title: "Modern India ",
    price: 350,
    category: "History",
    description: "This book is one of our bestsellers and is an effort to bring together various aspects of the turbulent period—from arrival of Europeans to India’s freedom from colonial rule—in a concise, all-inclusive, and systematic manner.",
    Author: "RAJIV AHIR",
    Publish: 2010,

    image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/w/t/t/modern-india-brief-history-spectrum-rajiv-ahir-2022-edition-original-imah2gjjjca5bdxb.jpeg?q=70&crop=false",
  },
  {
    id: 13,
    title: "History of the Lombards",
    price: 2280,
    category: "History",
    description: "History of the Lombards, by Paul the Deacon (c. 720-c. 799), is among the most important and oldest accounts of the Germanic nation. The book preserves many ancient myths and popular traditions and draws from sources that are now lost.",
    Author: "Deacon Paul the",
    Publish: 1514,

    image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/m/m/j/history-of-the-lombards-original-imagk4vg57quqzfu.jpeg?q=70&crop=false",
  },
  {
      id: 14,
      title: "Sunderkand ",
      price: 149,
      category: "Biography",
      description: "Sunderkand, believed to be the most beautiful (sunder) part of the Ramayana, describes Lord Hanuman's journey to Lanka. This book elucidates his pristine lifestyle, following which brings karmic and spiritual knowledge.",
      Author: "Tulsidas Goswami",
      Publish: 2020,
  
      image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/v/u/t/sunderkand-original-imagy328hfgbmasq.jpeg?q=70&crop=false",
    },
    {
        id: 15,
        title: "The Dhoni Touch",
        price: 215,
        category: "Biography",
        description: "Be it his signature helicopter shot or his ever-calm demeanour, Mahendra Singh Dhoni has always found a way to tap into the hearts of his fans. For someone who was training to be a footballer, who could have told that Mahi was going to take the world of cricket by storm.",
        Author: "Sundaresan Bharat",
        Publish: 2018,
    
        image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/f/4/j/the-dhoni-touch-original-imafy6yydqm2xydn.jpeg?q=70&crop=false",
      },
      {
        id: 16,
        title: "Light of Impossible Stars",
        price: 386,
        category: "Science fiction",
        description: "Award-winning author Gareth L. Powell delivers an explosive conclusion to his epic Embers of War trilogy. Low on fuel and hunted by the Fleet of Knives, the sentient warship Trouble Dog heads to the Intrusion-an area of space where reality .",
        Author: "Powell Gareth L",
        Publish: 2020,
    
        image: "https://rukminim2.flixcart.com/image/416/416/xif0q/book/r/6/8/light-of-impossible-stars-an-embers-of-war-novel-original-imaggewf5kyywnnf.jpeg?q=70&crop=false",
      },
];
